name: Build Docker Image

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The working directory to run the workflow in. E.g. `.`."
        required: true
        type: string
      dockerfile-path:
        description: "The path to the Dockerfile to build. E.g. `./Dockerfile`."
        required: true
        type: string
      image-name:
        description: "The name of the image to build. E.g. `my-image`"
        required: true
        type: string
      push:
        description: "Whether to push the built image to the registry."
        required: true
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Log in to GHCR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}
          tags: type=semver,pattern={{version}}

      - name: Build image
        if: ${{ !inputs.push }}
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.dockerfile-path }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=${{ runner.temp }}/image.tar

      - name: Build and push image
        if: ${{ inputs.push }}
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: ${{ inputs.working-directory }}
          file: ${{ inputs.dockerfile-path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: mode=max
          sbom: true

      - name: Upload image
        if: ${{ !inputs.push }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ inputs.image-name }}-image"
          path: ${{ runner.temp }}/image.tar
          retention-days: 1
