name: Common Cron Checks

on:
  workflow_call:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

permissions: write-all

jobs:
  sempgrep-scan:
    uses: ./.github/workflows/semgrep-scan.yaml
  trivy-scan:
    uses: ./.github/workflows/trivy-scan.yaml
  stale-check:
    uses: ./.github/workflows/stale-check.yaml
  # template-sync:
  #   uses: ./.github/workflows/template-sync.yaml
