name: Common Cron Checks

on:
  workflow_call:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

permissions: write-all

jobs:
  sempgrep-scan:
    uses: ./.github/workflows/semgrep-scan.yaml
  trivy-scan:
    uses: ./.github/workflows/trivy-scan.yaml
  stale-check:
    uses: ./.github/workflows/stale-check.yaml
    secrets: inherit

  # NOTE: At the moment, the template sync workflow is not suitable for running on a schedule since it completely replace
  # the files present in the repository with the ones from the template, which would lead to loss of any customizations made in the repository.
  # If we want to run it on a schedule, we would need to modify the workflow to only update the files that are different
  # from the template and preserve the customizations.
  # For now, please use the manual workflow.
  #
  # template-sync:
  #   uses: ./.github/workflows/template-sync.yaml
  #   secrets: inherit
