# NOTE: This workflow runs pre-commit checks with prek in workspace mode.
# When prek will introduce a way to import pre-commit configurations from other repositories (https://github.com/j178/prek/issues/1238)
# we can centralize all pre-commit checks in the repo-commons repository and reference the configuration file from there.

name: Pre-commit Checks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  pre-commit-checks:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run common pre-commit checks
        uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2.0.4
        with:
          extra-args: "--all-files --refresh"
