# NOTE: This workflow runs pre-commit checks with prek in workspace mode.
# When prek will introduce a way to import pre-commit configurations from other repositories (https://github.com/j178/prek/issues/1238)
# we can centralize all pre-commit checks in the repo-commons repository and reference the configuration file from there.

name: Pre-commit Checks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  pre-commit-checks:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run common pre-commit checks
        uses: j178/prek-action@6ad80277337ad479fe43bd70701c3f7f8aa74db3 # v2.0.3
        with:
          extra-args: "--all-files --refresh"
