name: Common Pull Request Checks

on:
  pull_request:
    branches:
      - "**"

permissions: write-all

jobs:
  common-pull-request-checks:
    uses: ./.github/workflows/common-pull-request-checks.yaml
    secrets: inherit
