name: Semgrep Scan

on:
  workflow_call:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  semgrep-scan:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:1.156.0@sha256:a3d49dc967b8534a6a76628e50c51cbfe33eb7195dc2feab1fdc0f100852c8ef
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Semgrep scan and generate SARIF report
        run: semgrep scan --config auto --sarif >semgrep.sarif

      - name: Upload Semgrep SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@b8bb9f28b8d3f992092362369c57161b755dea45 # v4.35.0
        with:
          sarif_file: semgrep.sarif
