name: Semgrep Scan

on:
  workflow_call:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  semgrep-scan:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:1.171.0@sha256:bdf7013b2c3634a487671158da77c554f531742326b543a9464d2adf6c433ac8
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Semgrep scan and generate reports
        shell: bash
        env:
          SEMGREP_EXCLUDED_RULES: |
            yaml.github-actions.security.secrets-inherit.secrets-inherit
        run: |
          EXCLUDE_RULE_ARGS=()

          while read -r rule; do
              [[ -z "$rule" ]] && continue
              EXCLUDE_RULE_ARGS+=(--exclude-rule "$rule")
          done <<<"$SEMGREP_EXCLUDED_RULES"

          if [[ -f .semgrepignorerule ]]; then
              while read -r rule; do
                  [[ -z "$rule" ]] && continue
                  EXCLUDE_RULE_ARGS+=(--exclude-rule "$rule")
              done <.semgrepignorerule
          fi

          semgrep scan \
              --config auto \
              --error \
              --text-output=semgrep.txt \
              --sarif-output=semgrep.sarif \
              "${EXCLUDE_RULE_ARGS[@]}"

      - name: Upload Semgrep txt file as artifact
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: semgrep.txt
          archive: false
          retention-days: 7

      - name: Upload Semgrep SARIF file for GitHub Advanced Security Dashboard
        if: always()
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v4.37.3
        with:
          sarif_file: semgrep.sarif
        continue-on-error: true
