name: Semgrep Scan

on:
  workflow_call:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  semgrep-scan:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:1.154.0@sha256:9fb6f44dc162b1e0aada85f072a95141844c61e3bfcedf40b8a46fecf208e986
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Semgrep scan and generate SARIF report
        run: semgrep scan --config auto --sarif >semgrep.sarif

      - name: Upload Semgrep SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
        with:
          sarif_file: semgrep.sarif
